### ISSUE TITLE
README miss react-use

### ISSUE THREAD

**Issue by FlorentJuif** [fabienjuif/use-locales#11]
Hi, 
I try to use use-locales and something happened: 
I have added dependencies "yarn add use-locales" but i have an error message like "can't find dependences"
And it seems we should add "react-use" too. I think it would be better if you tell it in your README

**Comment by fabienjuif** [comment]
When you install use-locales, it should tells you that you needs react-use since it is define in the package.json as a peerDependencies.

Can you check that?
